drop table items_de_despacho ;
drop table items_de_venta ;
drop table ingreso_items ;
drop table contenido_de_bodegas;
drop table notas_de_venta ;
drop table ordenes_de_despacho ;
drop table ingresos ;
drop table descuentos;
drop table productos ;
drop table usuarios ;
drop table clientes ;
drop table bodegas ;