from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('productos',
        url(r'create$', 'views.create_product_page'),
        url(r'get_nombre$','views.get_producto'),
        url(r'ingreso$','views.ingreso_producto_page'),
        url(r'transferencia$','views.transfer_producto_page'),
        url(r'createbodega$','views.create_bodega_page'),
        url(r'createcat$','views.create_cat_page'),
        url(r'ver$','views.ver_producto_page'),
        url(r'ver_resp$','views.ver_page'),
        url(r'create_regla$','reempaque.create_transform_page'),
        url(r'ver_reglas$','reempaque.ver_reglas_page'),
        url(r'mod_reglas$','reempaque.modificar_reglas'),
        url(r'ver_reglas_form$','reempaque.ver_reglas_form'),
        url(r'reempaque$','reempaque.reempaque_page'),
        url(r'mod_precio$','views.modificar_precio_page'),
        url(r'mod_prod$','mod_cant.mod_prod'),
        url(r'get_prod_cont$','views.get_cont'),
        url(r'buscar_producto$','views.buscar_producto'),
        url(r'recibir_prod$','views.procesar_transferencia'),
        url(r'transferencia_externa$','views.transfer_externa_page'),
        url(r'postear$','views.postear_transferencia'),
        url(r'postear_form$','views.postear_transferencia_form'),
        url(r'reenviar$','views.reenviar_trans'),
)
